Form/DataTransformer/CommaListTransformer.php
<?php
/**
 * Created by PhpStorm.
 * User: marco
 * Date: 19.09.14
 * Time: 16:21
 */

namespace Hn\EntityBundle\Form\DataTransformer;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;
use Symfony\Component\PropertyAccess\PropertyAccess;

class CommaListTransformer implements DataTransformerInterface
{
    private $manager;

    private $className;

    private $propertyPath;

    private $propertyAccessor;

    private $allowCreate;
    
    private static $newTags = [];

    public function __construct(ObjectManager $manager, $className, $propertyPath, $allowCreate)
    {
        $this->manager = $manager;
        $this->className = $className;
        $this->propertyPath = $propertyPath;
        $this->propertyAccessor = PropertyAccess::createPropertyAccessor();
        $this->allowCreate = $allowCreate;
    }

    /**
     * Transforms a value from the original representation to a transformed representation.
     *
     * This method is called on two occasions inside a form field:
     *
     * 1. When the form field is initialized with the data attached from the datasource (object or array).
     * 2. When data from a request is submitted using {@link Form::submit()} to transform the new input data
     *    back into the renderable format. For example if you have a date field and submit '2009-10-10'
     *    you might accept this value because its easily parsed, but the transformer still writes back
     *    "2009/10/10" onto the form field (for further displaying or other purposes).
     *
     * This method must be able to deal with empty values. Usually this will
     * be NULL, but depending on your implementation other empty values are
     * possible as well (such as empty strings). The reasoning behind this is
     * that value transformers must be chainable. If the transform() method
     * of the first value transformer outputs NULL, the second value transformer
     * must be able to process that value.
     *
     * By convention, transform() should return an empty string if NULL is
     * passed.
     *
     * @param mixed $value The value in the original representation
     *
     * @return string The value in the transformed representation
     *
     * @throws TransformationFailedException When the transformation fails.
     */
    public function transform($value)
    {
        if ($value === null) {
            return '';
        }

        $isTraversable = is_array($value) || $value instanceof \Traversable;
        if (!$isTraversable) {
            $type = is_object($value) ? get_class($value) : gettype($value);
            throw new TransformationFailedException("$type is not traversable");
        }

        $list = array();
        foreach ($value as $tag) {
            $className = $this->className;
            if ($tag instanceof $className) {
                $list[] = $this->propertyAccessor->getValue($tag, $this->propertyPath);
            } else {
                throw new TransformationFailedException("$tag is not a Tag");
            }
        }

        return implode(",", $list);
    }

    /**
     * Transforms a value from the transformed representation to its original
     * representation.
     *
     * This method is called when {@link Form::submit()} is called to transform the requests tainted data
     * into an acceptable format for your data processing/model layer.
     *
     * This method must be able to deal with empty values. Usually this will
     * be an empty string, but depending on your implementation other empty
     * values are possible as well (such as empty strings). The reasoning behind
     * this is that value transformers must be chainable. If the
     * reverseTransform() method of the first value transformer outputs an
     * empty string, the second value transformer must be able to process that
     * value.
     *
     * By convention, reverseTransform() should return NULL if an empty string
     * is passed.
     *
     * @param mixed $value The value in the transformed representation
     *
     * @return ArrayCollection The value in the original representation
     *
     * @throws TransformationFailedException When the transformation fails.
     */
    public function reverseTransform($value)
    {
        if ($value === "" || $value === null) {
            return new ArrayCollection();
        }

        $rawNames = preg_split("/\s*,\s*/", trim($value));
        $rawLowerCaseNames = array_unique(array_map('strtolower', $rawNames));

        /** @var EntityRepository $repository */
        $repository = $this->manager->getRepository($this->className);
        $qb = $repository->createQueryBuilder('tag');
        $qb->andWhere($qb->expr()->in("tag.$this->propertyPath", $rawLowerCaseNames));
        $tags = $qb->getQuery()->getResult();

        foreach ($tags as $tag) {
            $tagName = $this->propertyAccessor->getValue($tag, $this->propertyPath);
            $lowerCaseTagName = strtolower($tagName);
            foreach ($rawLowerCaseNames as $index => $rawLowerCaseName) {
                if ($rawLowerCaseName === $lowerCaseTagName) {
                    unset($rawNames[$index]);
                }
            }
        }

        if (!$this->allowCreate && !empty($rawNames)) {
            throw new TransformationFailedException("New tags found but wasn't allowed to create them");
        }

        foreach ($rawNames as $tagName) {
            if(isset(self::$newTags[strtolower($tagName)])) {
                $tags[] = self::$newTags[strtolower($tagName)];
                continue;
            }
            $tag = new $this->className();
            $this->propertyAccessor->setValue($tag, $this->propertyPath, $tagName);
            $tags[] = $tag;
            self::$newTags[strtolower($tagName)] = $tag;
        }

        return new ArrayCollection($tags);
    }
}

Form/DataTransformer/EmptyToNullTransformer.php
<?php
/**
 * Created by PhpStorm.
 * User: marco
 * Date: 13.10.14
 * Time: 11:07
 */

namespace Hn\EntityBundle\Form\DataTransformer;


use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

/**
 * Class EmptyToNullTransformer
 * @package Hn\EntityBundle\Form\DataTransformer
 * @todo this transformer should be applied to all checkboxes in the inline table form
 */
class EmptyToNullTransformer implements DataTransformerInterface
{
    /**
     * Transforms a value from the original representation to a transformed representation.
     *
     * This method is called on two occasions inside a form field:
     *
     * 1. When the form field is initialized with the data attached from the datasource (object or array).
     * 2. When data from a request is submitted using {@link Form::submit()} to transform the new input data
     *    back into the renderable format. For example if you have a date field and submit '2009-10-10'
     *    you might accept this value because its easily parsed, but the transformer still writes back
     *    "2009/10/10" onto the form field (for further displaying or other purposes).
     *
     * This method must be able to deal with empty values. Usually this will
     * be NULL, but depending on your implementation other empty values are
     * possible as well (such as empty strings). The reasoning behind this is
     * that value transformers must be chainable. If the transform() method
     * of the first value transformer outputs NULL, the second value transformer
     * must be able to process that value.
     *
     * By convention, transform() should return an empty string if NULL is
     * passed.
     *
     * @param mixed $value The value in the original representation
     *
     * @return mixed The value in the transformed representation
     *
     * @throws TransformationFailedException When the transformation fails.
     */
    public function transform($value)
    {
        return $value;
    }

    /**
     * Transforms a value from the transformed representation to its original
     * representation.
     *
     * This method is called when {@link Form::submit()} is called to transform the requests tainted data
     * into an acceptable format for your data processing/model layer.
     *
     * This method must be able to deal with empty values. Usually this will
     * be an empty string, but depending on your implementation other empty
     * values are possible as well (such as empty strings). The reasoning behind
     * this is that value transformers must be chainable. If the
     * reverseTransform() method of the first value transformer outputs an
     * empty string, the second value transformer must be able to process that
     * value.
     *
     * By convention, reverseTransform() should return NULL if an empty string
     * is passed.
     *
     * @param mixed $value The value in the transformed representation
     *
     * @return mixed The value in the original representation
     *
     * @throws TransformationFailedException When the transformation fails.
     */
    public function reverseTransform($value)
    {
        return $value === '' ? null : $value;
    }
}

Form/DeleteType.php
<?php
/**
 * Created by PhpStorm.
 * User: marcopfeiffer
 * Date: 02.07.14
 * Time: 12:59
 */

namespace Hn\EntityBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\ButtonTypeInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DeleteType extends AbstractType implements ButtonTypeInterface
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setRequired(array('redirect'));
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['redirect'] = $options['redirect'];
    }

    public function getParent()
    {
        return 'button';
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'hn_entity_delete';
    }
}

Form/EntityPlusType.php
<?php

namespace Hn\EntityBundle\Form;

use Doctrine\Common\Util\Debug;
use Doctrine\ORM\EntityManager;
use Hn\EntityBundle\Entity\BaseEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EntityPlusType extends AbstractType
{
    /** @var EntityManager */
    private $em;

    /**
     * @param EntityManager $em
     */
    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'modal_route' => null,
            'modal_route_parameters' => array()
        ));

        $resolver->setAllowedTypes(array(
            'modal_route' => array('string'),
            'modal_route_parameters' => array('array')
        ));
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        // gather information of the form this type is in
        $rootForm = $form->getRoot();
        $rootFormType = $rootForm->getConfig()->getType()->getInnerType();
        $view->vars['formType'] = $rootFormType->getName();
        $data = $rootForm->getData();

        if (! is_object($data)) {
            throw new \LogicException("The root form (which includes an entity_plus type) must have an entity as data. May be you should set the 'data_class' attribute of the root form");
        } else {
            // get the metadata for the root form data
            $meta = $this->em->getClassMetadata(get_class($data));
            if ($meta === null) {
                $type = is_object($data) ? get_class($data) : gettype($data);
                $formType = $view->vars['formType'];
                throw new \LogicException("entity_plus is used in $formType which doesn't has an Entity as data, got $type instead");
            }

            // identifier
            $ids = $meta->getIdentifierValues($data);
            if (count($ids) > 1) {
                throw new \LogicException("entity_plus can't handle entites with more than 1 identidier");
            }

            $view->vars['entityId'] = reset($ids);
            $view->vars['entityClass'] = $meta->getName();
        }

        // get options for modal request
        $view->vars['modalRoute'] = $options['modal_route'];
        $view->vars['modalRouteParameters'] = $options['modal_route_parameters'];
    }

    public function getParent()
    {
        return 'entity';
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'entity_plus';
    }
}

Form/InlineFormType.php
<?php
/**
 * Created by PhpStorm.
 * User: marcopfeiffer
 * Date: 03.07.14
 * Time: 17:51
 */

namespace Hn\EntityBundle\Form;


use Hn\EntityBundle\Service\EntityService;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Exception\UnexpectedTypeException;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Routing\RouterInterface;

class InlineFormType extends AbstractType
{
    /**
     * @var EntityService
     */
    private $entityService;

    /**
     * @var RouterInterface
     */
    private $router;

    function __construct(EntityService $entityService, RouterInterface $router)
    {
        $this->entityService = $entityService;
        $this->router = $router;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setRequired(array('form_type_class'));
    }


    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $formData = $form->getData();
        if (!is_object($formData)) {
            throw new UnexpectedTypeException($formData, 'entity');
        }

        if (!$this->entityService->getIdentifier($formData)) {
            throw new \RuntimeException("An entity must be persisted before it can be inline edited.");
        }

        $view->vars['submitPath'] = $this->router->generate('hn_entity_entity_updateproperty', array(
            'formTypeClass' => $options['form_type_class'],
            'formBaseName' => $form->getName(),
            'entityClass' => get_class($formData),
            'entityId' => $this->entityService->getIdentifier($formData)
        ));
    }

    protected function walkViews(FormView $currentView, FormView $rootView)
    {
        $currentView->vars['rootView'] = $rootView;

        foreach ($currentView as $childView) {

            if (!$childView instanceof FormView) {
                // this happens eg. for choices
                continue;
            }

            $this->walkViews($childView, $rootView);
        }
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $this->walkViews($view, $view);
    }

    public function getParent()
    {
        return 'form';
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'hn_entity_inline_form';
    }
}

Form/UpdateableEntityType.php
<?php
/**
 * Created by PhpStorm.
 * User: marcopfeiffer
 * Date: 03.07.14
 * Time: 17:51
 */

namespace Hn\EntityBundle\Form;


use Doctrine\Common\Util\Debug;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Routing\RouterInterface;

class UpdateableEntityType extends AbstractType
{
    /**
     * @var RouterInterface
     */
    private $router;

    function __construct(RouterInterface $router)
    {
        $this->router = $router;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        //Debug::dump($view->vars);

        $fullName = $view->vars['full_name'];

        if (!$options['rootFormType']) {
            $options['rootFormType'] = $form->getRoot()->getName();
        }

        $updateUrl = $this->router->generate('hn_entity_entity_submitformupdatepartial', array(
            'formType' => $options['rootFormType'],
            'propertyPath' => $fullName
        ));

        $view->vars['attr']['data-update-url'] = $updateUrl;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'rootFormType' => null
        ));
    }


    public function getParent()
    {
        return 'entity';
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'hn_updateable_entity';
    }
}

Resources/views/Form/delete.html.twig
{% block hn_entity_delete_widget %}
    {%- spaceless %}
        {% set redirect = form.vars.redirect %}
        {% set entity = form.parent.vars.value %}

        {% include 'HnEntityBundle:Dependency:deleteButton.html.twig' with { entity: entity, redirect: redirect } only %}
    {% endspaceless %}
{% endblock %}

Resources/views/Form/entity_plus.html.twig
{% block entity_plus_widget %}
    {% import 'HnLayoutBundle:macro:util.html.twig' as util %}

    {%- spaceless %}
        {% set className = (container_attr.class|default('') ~ ' input-group')|trim %}
        {% set container_attr = container_attr|default({})|merge({
            'class': className,
            'data-update-partial-url': path('hn_entity_entity_updatepartial', {
                'formType': formType,
                'propertyPath': full_name,
                'entityClass': entityClass,
                'entityId': entityId
            }),
            'data-modal-url': path(form.vars.modalRoute, form.vars.modalRouteParameters),
            'data-entity-class': entityClass
        }) %}

        <div {{ util.attributes(container_attr) }}>
            {{ form_widget(form) }}

            <span class="input-group-btn">
                {% if label is empty -%}
                    {% set label = name|humanize %}
                {%- endif -%}
                <button type="button" class="btn btn-default"
                        data-toggle="tooltip" data-placement="left"
                        title="{{ ('entity_plus.plus.' ~ name)|trans({ '%label%': label }) }}">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            </span>
        </div>
    {% endspaceless %}
{% endblock %}

Resources/views/Form/inline_table_theme.html.twig
{% block form_start %}{% endblock %}
{% block form_end %}{% endblock %}

{% block form_widget_simple %}
    {%- spaceless %}
        {% set rootForm = form.vars.rootView %}
        {% set type = type|default('text') %}
        {#<input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>#}
        {% set className = (attr.class|default('') ~ ' editable')|trim %}
        {% if text_value|default(value) is empty %}
            {% set className = className ~ ' text-muted' %}
        {% endif %}
        {% set attr = attr|merge({
            'data-url': rootForm.vars.submitPath,
            'data-send': 'always',
            'data-name': full_name,
            'data-type': type,
            'data-value': value,
            'data-placement': placement|default('bottom'),
            'data-emptytext': attr.placeholder|default('empty')|trans,
            'data-emptyclass': 'text-muted',
            'class': className,
            'href': attr.href|default('#')
        }) %}
        <a {{ block('widget_container_attributes') }}>
            {{- text_value|default(value)|default(attr.placeholder|default('empty')|trans) -}}
        </a>
    {% endspaceless %}
{% endblock %}

{% block hidden_widget %}
    {% set rootForm = form.vars.rootView %}
    {% set submitPath = rootForm.vars.submitPath %}
    {% set submit_script -%}
    var $this = jQuery(this);
    var req = jQuery.post({{ submitPath|json_encode|raw }}, {{ (full_name ~ '=')|json_encode|raw }} + encodeURIComponent($this.val()));
    req.fail(function(msg){ alert(msg) });
    {%- endset %}
    <input type="hidden" {{ block('widget_attributes') }}
           onchange="{{ submit_script|e }}" {% if value is not empty %}value="{{ value }}" {% endif %}/>
{% endblock hidden_widget %}

{% block textarea_widget %}
    {%- set type = 'textarea' -%}
    {{- block('form_widget_simple') -}}
{% endblock textarea_widget %}

{% block form_row %}
    {{- form_widget(form) -}}
{% endblock %}

{% block choice_widget_collapsed %}
    {%- spaceless %}
        {% set choiceArray = [] %}
        {% set type = 'select2' %}
        {% set text_value = '' %}
        {% if empty_value is not none %}
            {% set choiceArray = choiceArray|merge([{ 'value': '', 'text': empty_value|trans }]) %}
        {% endif %}
        {% for choice in choices %}
            {% set choiceArray = choiceArray|merge([{
            'value': choice.value,
            'text': choice.label|trans({}, translation_domain)
            }]) %}
            {% if choice is selectedchoice(value) %}
                {% set text_value = choice.label|trans({}, translation_domain) %}
            {% endif %}
        {% endfor %}
        {% set attr = attr|merge({
        'data-source': choiceArray|json_encode,
        'data-select2': { dropdownAutoWidth: true, width: 'element' }|json_encode,
        'placeholder': empty_value|default('empty'|trans)
        }) %}
        {{ block('form_widget_simple') }}
    {% endspaceless %}
{% endblock choice_widget_collapsed %}

{% block date_widget %}
    {%- spaceless %}
        {% set type = 'date' %}
        {% set attr = attr|merge({
            'data-format': 'dd.mm.yyyy',
            'data-viewformat': 'dd.mm.yyyy'
        }) %}
        {{ block('form_widget_simple') }}
    {% endspaceless %}
{% endblock date_widget %}

{% block choice_widget_expanded -%}
    <div {{ block('widget_container_attributes') }}>
        {%- for child in form %}
            {{- form_row(child) -}}
        {% endfor -%}
    </div>
{% endblock choice_widget_expanded %}

{% block checkbox_widget %}
    {% spaceless %}
        {% set rootForm = form.vars.rootView %}
        {% set submitPath = rootForm.vars.submitPath %}
        {% set submit_script -%}
        var $this = jQuery(this);
        var $all = jQuery('[name={{ full_name|json_encode|raw }}]');
        $all.prop({disabled: true});
        var req = jQuery.post({{ submitPath|json_encode|raw }}, {{ (full_name ~ '=')|json_encode|raw }} + ($this.is(':checked') ? $this.val() : ''));
        req.done(function(){ $all.prop({disabled: false}) });
        req.fail(function(msg){ alert(msg) });
        {%- endset %}
        <input type="{{ type|default('checkbox') }}" onchange="{{ submit_script|e }}"
                {{ block('widget_attributes') }}
                {%- if value is defined %} value="{{ value }}"{% endif %}
                {%- if checked %} checked="checked"{% endif %} />
    {% endspaceless %}
{% endblock checkbox_widget %}

{% block radio_widget %}
    {%- set type = 'radio' -%}
    {{- block('checkbox_widget') -}}
{% endblock radio_widget %}

{% block checkbox_row %}
    {%- spaceless %}
        <div class="{{ type|default('checkbox') }}{% if disabled %} disabled{% endif %}">
            {% if label is not sameas(false) -%}

                {% if required -%}
                    {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
                {%- endif %}
                {% if label is empty -%}
                    {% set label = name|humanize %}
                {%- endif -%}

                <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
                {{- form_widget(form) -}}
                {{- label|trans({}, translation_domain) -}}
                </label>
            {% else %}
                {{- form_widget(form) -}}
            {%- endif %}
        </div>

        {{ form_errors(form) }}
    {% endspaceless %}
{% endblock checkbox_row %}

{% block radio_row %}
    {%- set type = 'radio' -%}
    {{- block('checkbox_row') -}}
{% endblock radio_row %}

Resources/views/Form/tag.html.twig
{# for this to work, it requires a script like this one #}
{# https://gist.github.com/Nemo64/9249376 #}
{% block hn_entity_tag_widget %}
    {%- spaceless %}
        {% set class_name = (attr.class|default('') ~ ' js-select2')|trim %}
        {% set attr = attr|merge({
        'class': class_name,
        'data-tags': form.vars.tags|json_encode,
        'data-minimum-input-length': minimum_input_length|json_encode,
        'data-maximum-input-length': maximum_input_length|json_encode,
        'data-token-separators': token_separators|json_encode
        }) %}
        {{ block('form_widget_simple') }}
    {% endspaceless %}
{% endblock hn_entity_tag_widget %}